values = input('Enter a string: ')
result = values.split(' ')
print(result)
result = values.split(' ' ,1 )
print(result)
result = values.split(' ' ,3 )
print(result)
result = values.split(' ' ,20 )
print(result)